// [Providers]
import {
  AsyncStateProvider
} from "@omariosouto/common-ui-web/state";
import {
  FrameworkProvider,
  RootErrorBoundary,
  ThemeProvider
} from "@omariosouto/common-ui-web/components";
// ==============================================================
import "@omariosouto/common-ui-web/globals.css";
import "./globals.css";
// ==============================================================
import { Link, useRouter } from ".setup/framework";
import { HttpClientDashoard } from "../.setup/http";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en-US" suppressHydrationWarning>
      <body>
        <RootErrorBoundary>
          <HttpClientDashoard />
          <AsyncStateProvider>
            <ThemeProvider
              defaultTheme="theme-default-light"
            >
              <FrameworkProvider
                useRouter={useRouter}
                LinkComponent={Link}
              >
                {children}
              </FrameworkProvider>
            </ThemeProvider>
          </AsyncStateProvider>
        </RootErrorBoundary>
      </body>
    </html>
  )
}